spring.application.name=Library Example Service

# Database Configuration
# Keep DB alive between connections in the same JVM
spring.datasource.url=jdbc:h2:mem:librarydb;DB_CLOSE_DELAY=-1;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# H2 Console (for debugging)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Flyway
spring.flyway.locations=classpath:db/migration

# Logging
logging.level.org.springframework.jdbc=DEBUG
logging.level.org.jooq=DEBUG
logging.level.org.flywaydb=DEBUG
